### ISSUE TITLE
BUG: Variable on right hand of assignment not renamed in scripts

### ISSUE THREAD

**Issue by normano** [cherriesandmochi/gdmaim#1]
If you include Tracer addon and export the project PCK and inspect the code. You will see "new_thread_id" is not replaced on the right hand of the assignment even though the function parameter with new_thread_id was renamed. This happens on various scripts.

You can find tracer at https://github.com/wyvernbw/tracer.gd to include into a project as addon to try.

**Comment by cherriesandmochi** [comment]
Thank you very much for the bug report!
Seems like I didn't think of that kind of formatting for function parameters. None of the parameters in that function seem to get detected. I already have a good idea why that happens, should be fixed tomorrow.

**Comment by cherriesandmochi** [comment]
Thanks again for the bug report!

**Comment by cherriesandmochi** [comment]
Glad to hear that and thanks for helping with testing!
Oh wow, I completely forgot about treating the semicolon as delimeter! The sample project you gave me does seem to work now, scheduled_task and task_scheduler at least look fine to me now.
