### ISSUE TITLE
Question: Does it work on scene's built-in GDScript?

### ISSUE THREAD

**Issue by Ayzurus** [cherriesandmochi/gdmaim#16]
Hey @cherriesandmochi,
First of all, great work that you're doing here, thanks!

I made a quick test run with the obfuscate on a somewhat big project I have, but the game broke on certain scenes.

Those scenes use built-in scripts, as to not clutter the source folder, since they are short and a singular cases, but the console throws a lot of errors about not finding certain variables and functions, indeed because they are no longer named the same way.

Whence the question.

**Comment by Ayzurus** [comment]
I think I just found the answer on the README, Although I read it all before, I somehow missed it. Sorry for the trouble.

**Comment by cherriesandmochi** [comment]
Thanks!
Yea, built-in scripts are currently not being supported. Though that might be something I'll think about adding with the obfuscator rewrite.
