### ISSUE TITLE
BUG: enums assigned to constants are not being evaluated correctly

### ISSUE THREAD

**Issue by normano** [cherriesandmochi/gdmaim#2]
When [window.gd](https://github.com/normano/gdmain_experiment/blob/a86a0a4325934b6d85cef0a9037683c8c96ccad9/window.gd#L5) is obfuscated, you will see something like this:
```
const __w7HZ = Tracer.__1Gf0;

var __QSTr = __w7HZ.Info | __w7HZ.Warn | __w7HZ.Error;
```

Wth inline enums turned on, there is no longer a enum so cannot reference by constant, so I turned it off. After that the INFO/WARN/ERROR are still not replaced with the renamed enums.

**Comment by cherriesandmochi** [comment]
I'm gonna take a look at it in a short while, just want to finish something first.

**Comment by cherriesandmochi** [comment]
Line breaks before functions seem to have gotten fixed by one of the lambda changes I made.

I see now why those enum values values do not get renamed; enum values only work when they are getting accessed directly. Since constants are being evaluated before obfuscation anyways, "loading" all the enum values into constants like that should be fairly trivial.

Thanks for all the help!

**Comment by cherriesandmochi** [comment]
Changed the description to better match the issue. Hope you don't mind!
Anyway, I'm going to stop here for today and continue working on it tomorrow.

**Comment by cherriesandmochi** [comment]
Fixed by b852b4dfd3c50b3ed5b1ef5931e8fa29a2bc6337

**Comment by cherriesandmochi** [comment]
> I changed const to var today and the problem persists, so it is not limited to const.

Not being able to assign inlined enums to variables is unfortunately an expected limitation. And honestly, I don't see why you would ever assign an enum to a variable instead of a constant, so I don't really want to spend time on that right now.

**Comment by cherriesandmochi** [comment]
Thanks for the report! This ended up being way more convoluted than I thought it would be. I hope the fix didn't break anything else, though it still works fine on my game.
