### ISSUE TITLE
buttons do not work

### ISSUE THREAD

**Issue by cenullum** [cherriesandmochi/gdmaim#20]
Any button doesnt work in the project. I use linux mint and godot last stable 4.3 version. Pressed signals were connected via inspector, is this problem?

I tested  main and 0.1.1 build. same result

**Comment by cherriesandmochi** [comment]
Are your scenes saved as binary files("*.scn")?
Scenes containing signal connections or obfuscated export vars must be saved as text files("*.tscn").

**Comment by cenullum** [comment]
Every scene in the project is .tscn

**Comment by cherriesandmochi** [comment]
My best guess is that your signals are connected to an embedded script, which aren't supported.

**Comment by cenullum** [comment]
[testtststs.tar.gz](https://github.com/user-attachments/files/17025176/testtststs.tar.gz)
I tested on a button that gets its script from files then connected all signals to its script. Dont work on build but on editor its works.   Buttons theme works when hovering and pressing button it changes its colors and images  but not signal works

**Comment by cherriesandmochi** [comment]
Ah okay, I finally figured it out. You had the RegEx filter enabled but no RegEx expression set, thus every single line from every script had been stripped off. I guess it makes sense to ignore the RegEx expression if it is empty.

**Comment by cherriesandmochi** [comment]
Thanks!

**Comment by cenullum** [comment]
![image](https://github.com/user-attachments/assets/40a2f871-5805-4ac7-8e67-4d0d89cafc89)

![image](https://github.com/user-attachments/assets/0c251b4f-9fef-49c6-949b-5ba722b16f74)
.I tried new code still same. it seems on_pressed converted to _RmGh in .tscn but script is empty. maybe script seems empty because of source map viewer because my other functions were working in my main project

![image](https://github.com/user-attachments/assets/41f4117a-b7a9-424f-99f5-f84ee4ea54e0)
Then I disabled and enabled all of settings same result.



![Peek 2024-09-17 22-20](https://github.com/user-attachments/assets/c198ec72-005b-4ef5-9d68-fe3220eaa51e)
![Peek 2024-09-17 22-19](https://github.com/user-attachments/assets/63f5376a-3812-436a-b827-c29ae327e922)

**Comment by cherriesandmochi** [comment]
Ohh I completely forgot that 4.3 reintroduced binary tokenization of scripts. My bad. The plugin now pushes an error when binary tokenization is enabled.
So yea, to fix your issue, set the export mode of scripts to "Text" in your export template.

**Comment by cenullum** [comment]
![image](https://github.com/user-attachments/assets/999bb88f-a8ad-4635-b095-dcc2af1f2d58)
![image](https://github.com/user-attachments/assets/9d38abf6-a9c7-4481-861e-ff5d3a36ccf9)


works fine. what are the disadvantages of making this setting? I was expecting the order of functions and variables to be different in the export, but why is it in the same order?
![image](https://github.com/user-attachments/assets/ca184672-ad97-4f94-84f4-4fba5bd6010a)

**Comment by cherriesandmochi** [comment]
It _should_ shuffle the order, not sure why it doesn't as it works on my end. Perhaps some really unlucky rng?
What happens if you add/remove declarations? If it still doesn't work, could you share your settings please?

**Comment by cenullum** [comment]
not sure why works now. maybe because of different seed or I reloaded the project 
![image](https://github.com/user-attachments/assets/8bc96f09-561c-4c22-962d-1ea6cd5ea48a)


when I set script export mode as text does it become more easy to reverse engineering?
If there is a discord I can ask quick questions there. I don't want to clutter this section unnecessarily.

**Comment by cherriesandmochi** [comment]
> when I set script export mode as text does it become more easy to reverse engineering? 
Well it means that all scripts are stored in plain text, but tokenized scripts can be easily reversed anyway, so obfuscation definitely beats just tokenized scripts imo.

> If there is a discord I can ask quick questions there. I don't want to clutter this section unnecessarily.
There isn't, but I sent you my discord via dm.
