### ISSUE TITLE
The Internal scripts were not processed

### ISSUE THREAD

**Issue by HowQi** [cherriesandmochi/gdmaim#25]
This kind of script is rarely used. I don't know whether it is easy to handle this kind of script.Anyway, I wrote this issue.
(Is it called internal script in English? It is set up like this.)
![图片](https://github.com/user-attachments/assets/bee3dda0-de6a-45d3-8ca5-1f29d1fd54fa)

**Comment by cherriesandmochi** [comment]
Yea internal scripts aren't supported right now, though it shouldn't be that hard to do so.
It's something I'm planning to do eventually.

**Comment by cherriesandmochi** [comment]
> The internal scripts may be processed soon in case anyone ever needs it, i have made some changes and tested both the PackedScenes and Resources, Thank you for opening this topic.
> 
> Pull ref: #30

Oh I completely forgot to close this issue.
I already merged your PR. Thanks!
