### ISSUE TITLE
The word `Vector2.DOWN` is wrongly obscured in some cases.

### ISSUE THREAD

**Issue by HowQi** [cherriesandmochi/gdmaim#26]
Like `DOWN`, there are other directions of `Vector2` that are mishandled.

This is probably because I created another script with `UP`  `DOWN` `LEFT` `RIGHT` members.

Can I only avoid it? Maybe it's a problem, so I wrote this issue.

**Comment by cherriesandmochi** [comment]
Oh ye, I forgot to add the constants of variants as exceptions.
Easy to fix, thanks!
