### ISSUE TITLE
Chinese characters are not considered as suitable identifier.

### ISSUE THREAD

**Issue by HowQi** [cherriesandmochi/gdmaim#27]
```
func _is_valid_identifier(char : String) -> bool:
	return IDENTIFIER_CHARACTERS.contains(char)
```

I occasionally use Chinese characters as variable names. 
Many years ago, variable name with non-English letters was not available, but now most IDE supports it, including Godot.
As far as I know, there are many users who program in pure Chinese at present, and the feature may help them.
In addition, some designers may convert design tables in natural language into code, and this feature will help them.

I don't know how to confirm all the available identifiers at one time. Maybe it can wait users in different languages ask for more requirements. This is my practice:

```
func _is_valid_identifier(char : String) -> bool:
	return IDENTIFIER_CHARACTERS.contains(char) or _is_han(char)

func _is_han(char:String) -> bool:
	var num = char.unicode_at(0)
	return num >= 0x4e00 and num <= 0x9fcb
```
This range covers frequently used Chinese characters and some infrequently used Chinese characters, which should be enough.Characters that are not considered may only appear in garbled words in general.

Maybe you can also consider popular languages such as Japanese.

**Comment by cherriesandmochi** [comment]
Yea that was supposed to be a temporary way of detecting identifiers, as I knew it would run into trouble with other characters.
Completely forgot about it, oops.
Godot does conveniently have the `String.is_valid_identifier()` function, so that should do the trick. I'm gonna do some testing first though.
